In [1]:
# Given an array nums and a target value k, find the maximum length of a subarray that sums to k. 
# If there isn't one, return 0 instead.

In [1]:
import numpy as np
class Solution(object):
    def maxSubArrayLen(self, nums, k):
        """
        :type nums: List[int]
        :type k: int
        :rtype: int
        """
        N = len(nums)
        if N == 0:
            return 0
        
        max_len = 0      # initial
        sums = np.zeros((N,N))
        for i in range(N):
            sums[i:,0:i] += nums[i]  # fill in col of numbers
            loc = np.where(sums[i,:] == k)
            try:
                temp = abs(loc[0][0] - i)
            except:
                temp = 0
            if temp > max_len:
                max_len = temp
        return max_len

In [26]:
# if do not use numpy but very expensive
class Solution(object):
    def maxSubArrayLen(self, nums, k):
        """
        :type nums: List[int]
        :type k: int
        :rtype: int
        """
        N = len(nums)
        if N == 0:
            return 0
        length = []
        
        for i in range(N):
            for j in range(i, N):
                 if sum(nums[i:j+1]) == k:
                        length.append(j-i+1)
        if length == []:
            return 0
        return max(length)
                

In [ ]:
# Well, Not really understand
class Solution(object):
    def maxSubArrayLen(self, nums, k):
        """
        :type nums: List[int]
        :type k: int
        :rtype: int
        """

        max_len, acc = 0, 0
        mp = {0:-1}
        
        for i in xrange(len(nums)):
            acc += nums[i]
            if acc not in mp:
                mp[acc] = i
            if acc-k in mp:
                result = max(result, i - dic[acc-k])
                
        return result

In [27]:
nums = [-1]
k = -1
Solution().maxSubArrayLen(nums, k)

1

In [23]:
nums[0:0]

[]

In [34]:
sums = np.zeros((4,4))

In [12]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setslice__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [38]:
i = 3
sums[i:,0:i] += i

In [39]:
print sums

[[ 0.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 3.  2.  0.  0.]
 [ 6.  5.  3.  0.]]


In [41]:
loc = np.where(sums[2,:] == 1)
try:
    print loc[0][0]
    max_len = abs(loc[0][0] - i)
except:
    max_len = 0
print max_len

0


In [17]:
max([-1])

-1